In [2]:
import numpy as np
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import warnings
warnings.filterwarnings("ignore")

In [5]:
df = pd.read_csv('/content/drive/MyDrive/DataScience/trab1/cursos-prouni.csv - cursos-prouni-2018-tratados.csv.csv',
                    )

In [6]:
df.head()

grau     turno  mensalidade  bolsa_integral_cotas  \
0  Bacharelado  Integral      9715.61                   2.0   
1  Bacharelado  Integral      9674.34                   4.0   
2  Bacharelado  Integral      9023.07                   4.0   
3  Bacharelado  Integral      8508.54                   2.0   
4  Bacharelado  Integral      8281.38                   3.0   

   bolsa_integral_ampla  bolsa_parcial_cotas  bolsa_parcial_ampla  \
0                   5.0                  6.0                 10.0   
1                   1.0                  5.0                  2.0   
2                   4.0                  5.0                  5.0   
3                   1.0                  7.0                  2.0   
4                   1.0                  6.0                  2.0   

          curso_id curso_busca cidade_busca uf_busca  \
0    1002328574024    Medicina    Sao Paulo       SP   
1   65899611932754    Medicina   Rio Branco       AC   
2   65921511844324    Medicina    Itaperuna       RJ   
3  104123711716094    Medicina        Belem       PA   
4  105887911921884    Medicina   Imperatriz       MA   

                             universidade_nome      nome  nota_integral_ampla  \
0    Universidade Cidade de São Paulo - UNICID  Medicina               739.62   
1          Faculdade Barão do Rio Branco - FAB  Medicina               758.32   
2             Faculdade Redentor - FACREDENTOR  Medicina               741.06   
3  Faculdade Metropolitana da Amazônia - FAMAZ  Medicina               741.36   
4  Universidade do Ceuma - Uniceuma - UNICEUMA  Medicina               756.46   

   nota_integral_cotas  nota_parcial_ampla  nota_parcial_cotas  
0               738.08              738.96              718.64  
1               723.94              734.92              711.26  
2               729.02              730.98              722.82  
3               739.90              760.80              715.10  
4               737.88              747.14              717.60

In [7]:
list_drop_columns = ['grau',
                     'turno',
                     'nome',
                     'curso_id',
                     'nota_parcial_ampla',
                     'nota_parcial_cotas',
                     'nota_integral_ampla',
                     'nota_integral_cotas',
                     'mensalidade',
                     'cidade_busca',
                     'uf_busca',
                    'universidade_nome',
                     ]

df_aux = df.drop(columns=list_drop_columns)
df_aux.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2203 entries, 0 to 2202
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   bolsa_integral_cotas  2203 non-null   float64
 1   bolsa_integral_ampla  2203 non-null   float64
 2   bolsa_parcial_cotas   2203 non-null   float64
 3   bolsa_parcial_ampla   2203 non-null   float64
 4   curso_busca           2203 non-null   object 
dtypes: float64(4), object(1)
memory usage: 86.2+ KB


In [8]:
df_aux.head()

bolsa_integral_cotas  bolsa_integral_ampla  bolsa_parcial_cotas  \
0                   2.0                   5.0                  6.0   
1                   4.0                   1.0                  5.0   
2                   4.0                   4.0                  5.0   
3                   2.0                   1.0                  7.0   
4                   3.0                   1.0                  6.0   

   bolsa_parcial_ampla curso_busca  
0                 10.0    Medicina  
1                  2.0    Medicina  
2                  5.0    Medicina  
3                  2.0    Medicina  
4                  2.0    Medicina

In [9]:
# Label Encoder

from sklearn.preprocessing import LabelEncoder

In [10]:
df_aux.head()

bolsa_integral_cotas  bolsa_integral_ampla  bolsa_parcial_cotas  \
0                   2.0                   5.0                  6.0   
1                   4.0                   1.0                  5.0   
2                   4.0                   4.0                  5.0   
3                   2.0                   1.0                  7.0   
4                   3.0                   1.0                  6.0   

   bolsa_parcial_ampla curso_busca  
0                 10.0    Medicina  
1                  2.0    Medicina  
2                  5.0    Medicina  
3                  2.0    Medicina  
4                  2.0    Medicina

In [11]:
df_pca = df_aux.iloc[:,:].values
df_pca

array([[2.0, 5.0, 6.0, 10.0, 'Medicina'],
       [4.0, 1.0, 5.0, 2.0, 'Medicina'],
       [4.0, 4.0, 5.0, 5.0, 'Medicina'],
       ...,
       [1.0, 1.0, 1.0, 3.0, 'Pedagogia'],
       [1.0, 2.0, 1.0, 9.0, 'Gestão da Qualidade'],
       [1.0, 2.0, 2.0, 5.0, 'Marketing']], dtype=object)

In [12]:
le = LabelEncoder()
df_pca = le.fit_transform(df_pca[:,1])
df_pca

array([4, 0, 3, ..., 0, 1, 1])

In [13]:
list(le.classes_)

[1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 16.0,
 17.0,
 18.0,
 19.0,
 22.0,
 50.0]

In [14]:
df_aux['curso_busca'] = df_pca
df_aux.head()

bolsa_integral_cotas  bolsa_integral_ampla  bolsa_parcial_cotas  \
0                   2.0                   5.0                  6.0   
1                   4.0                   1.0                  5.0   
2                   4.0                   4.0                  5.0   
3                   2.0                   1.0                  7.0   
4                   3.0                   1.0                  6.0   

   bolsa_parcial_ampla  curso_busca  
0                 10.0            4  
1                  2.0            0  
2                  5.0            3  
3                  2.0            0  
4                  2.0            0

In [15]:
inverted = le.inverse_transform(df_pca)
print(inverted)

[5.0 1.0 4.0 ... 1.0 2.0 2.0]


In [16]:
from sklearn.decomposition import PCA

In [17]:
pca = PCA(n_components=2)

In [18]:
pca_transform = pca.fit_transform(df_aux)

In [19]:
pca_transform.shape

(2203, 2)

In [20]:
# Componentes principais
pca_transform

array([[ 3.10872938,  3.58002407],
       [-5.10351642,  1.96676904],
       [-1.93742676,  3.33246641],
       ...,
       [-4.38758826, -2.62758716],
       [ 1.65527004, -2.51507906],
       [-2.283314  , -1.39988715]])

In [21]:
# razão das variáveis explicativas
pca.explained_variance_ratio_

array([0.87799444, 0.09531181])

In [22]:
# Soma das variáveis explicativas
pca.explained_variance_ratio_.sum()

0.9733062495436438

In [23]:
import plotly.express as px

In [25]:
labels = {
    str(i): f"PC {i+1} ({var:.1f}%)"
    for i, var in enumerate(pca.explained_variance_ratio_ * 100)
}

fig = px.scatter_matrix(
    pca_transform,
    labels=labels,
    dimensions=range(2),
    color=df_aux["curso_busca"]
)
fig.update_traces(diagonal_visible=False)
fig.show()